language: generic

os: linux
dist: bionic

env:
  global:
    - LUAROCKS_VERSION=3.4.0
    - VIPS_VERSION=8.10.2
    - VIPS_WARNING=0
    - JOBS=`nproc`
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PATH=$HOME/vips/bin:$HOME/luarocks/bin:/usr/local/openresty/luajit/bin:$PATH

cache:
  directories:
    - $HOME/vips
    - $HOME/luarocks

addons:
  apt:
    sources:
      # Use the official APT repositories from OpenResty, because LuaJIT on bionic is quite old
      - sourceline: 'deb http://openresty.org/package/ubuntu $(lsb_release -cs) main'
        key_url: 'https://openresty.org/package/pubkey.gpg'
    packages:
      - openresty
      - libcfitsio-dev
      - libexif-dev
      - libexpat1-dev
      - libfftw3-dev
      - libgif-dev
      - libgsf-1-dev
      - libgsl-dev
      - liblcms2-dev
      - libmagickwand-dev
      - libmatio-dev
      - libnifti-dev
      - libopenexr-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpng-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libtiff5-dev
      - libwebp-dev

before_install:
  - bash .ci/install-vips.sh 
  - bash .ci/install-luarocks.sh
    --with-lua=/usr/local/openresty/luajit/
    --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
  - eval `luarocks path`

install:
  - make dev

script:
  - make lint
  - make test
